# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["sheldon", "chezmoi", "tlmgr", "conda"]

# Ignore failures for these steps
ignore_failures = ["helm", "node", "gem", "tlmgr", "ruby_gems",]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
#no_retry = true

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Path to Topgrade executable on remote machines
#remote_topgrade_path = [".cargo/bin/topgrade"]

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title
#set_title = false

# Cleanup temporary or old files
#cleanup = true

#[git]
#max_concurrency = 5
# Additional git repositories to pull
#repos = [
#    "~/src/*/",
#    "~/.config/something"
#]

# Don't pull the predefined git repos
#predefined_repos = false

# Arguments to pass Git when pulling Repositories
#arguments = "--rebase --autostash"

#[composer]
#self_update = true

# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
#"Pip Environment" = "~/.pyenv/shims/pip install -U --upgrade-strategy eager pip requests flake8"
# "Updating Homebrew Bundle" = "brew bundle -f --global dump"
# "ASDF upgrades - terraform" = "asdf install terraform latest:0.14; asdf global terraform `asdf latest terraform 0.14`"
# "ASDF upgrades - terragrunt" = "asdf install terragrunt latest; asdf global terragrunt `asdf latest terragrunt`"
# "ASDF upgrades - python" = "asdf install python latest:3.9; asdf global python `asdf latest python 3.9`"

#[brew]
#greedy_cask = true
